owner: Neonovplay
repo: panel_frustrator
sites:
  - name: VPN Panel
    url: https://vpn.frustrator.ru
    expectedStatusCodes:
      - 200
      - 401
status-website:
  cname: uptime.frustrator.ru
  name: Frustrator Status
  description: Мониторинг серверов
  theme: dark
