owner: Neonovplay
repo: panel_frustrator
sites:
  - name: VPN Panel
    url: https://panel.frustrator.ru
  - name: VPN Server
    url: https://panel.frustrator.ru
    expectedStatusCodes:
      - 200
      - 401
status-website:
  cname: status.frustrator.ru
  name: Frustrator Status
  description: Мониторинг серверов
