owner: Neonovplay
repo: panel_frustrator
sites:
  - name: VPN Panel
    url: https://vpn.frustrator.ru
    expectedStatusCodes:
      - 200
      - 401
  - name: VPN Panel Login
    url: https://vpn.frustrator.ru/login
    expectedStatusCodes:
      - 200
  - name: SSH
    check: tcp-ping
    url: 91.108.248.129
    port: 22
status-website:
  cname: uptime.frustrator.ru
  name: Frustrator Status
  description: Мониторинг серверов
  theme: dark
